# Generated by Django 4.0.4 on 2022-05-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='path',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
